import { getCheck, postAdminLogin } from "./authAPI";
import { Status } from "@/enums";
import { AppState } from "@/store";
import { message, setAuthToken } from "@/utils";
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { Admin, Message } from "@types";

interface AuthState {
    token: string | null;
    data: Admin | null;
    role?: string;
    status: Status;
    message: Message | null;
}

const initialState: AuthState = {
    token: null,
    data: null,
    status: Status.IDLE,
    message: null,
};

export const check = createAsyncThunk("auth/check", async () => {
    const token = localStorage.getItem("token");
    if (token) {
        setAuthToken(token);
        return await getCheck();
    }
});
const checkAuthTimeout = createAsyncThunk(
    "auth/timeout",
    (expirationTime: number) => {
        setTimeout(() => logout(), expirationTime);
    }
);
export const adminLogin = createAsyncThunk(
    "auth/admin/login",
    async (data: { email: string; password: string }) =>
        await postAdminLogin(data)
);

const dataLoading = (state: AuthState) => {
    state.status = Status.LOADING;
};

export const authSlice = createSlice({
    name: "auth",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        logout: (state) => {
            setAuthToken();
            localStorage.removeItem("token");
            localStorage.removeItem("expirationDate");

            state.token = null;
            state.data = null;
            state.status = Status.IDLE;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(check.pending, dataLoading)
            .addCase(check.fulfilled, (state, action) => {
                if (action.payload && action.payload.data) {
                    if (!("content" in action.payload.data)) {
                        const token = localStorage.getItem("token");

                        setAuthToken(token);
                        state.token = token;
                        delete action.payload.data.password;
                        state.data = action.payload.data;
                        state.role = action.payload.role;
                        state.status = Status.IDLE;

                        checkAuthTimeout(
                            new Date(
                                localStorage.getItem("expirationDate")!
                            ).getTime() - new Date().getTime()
                        );
                    }
                } else {
                    setAuthToken();
                    state.token = null;
                    state.data = null;
                    state.role = undefined;
                    state.status = Status.FAILED;
                }
            })
            .addCase(check.rejected, (state, action) => {
                if (
                    action.error.message &&
                    action.error.message.includes("401")
                ) {
                    setAuthToken();
                    localStorage.removeItem("token");
                    localStorage.removeItem("expirationDate");
                    location.reload();
                }
                state.token = null;
                state.data = null;
                state.status = Status.FAILED;
            })

            .addCase(adminLogin.pending, dataLoading)
            .addCase(adminLogin.fulfilled, (state, action) => {
                if ("content" in action.payload.data)
                    state.message = action.payload.data;
                else {
                    localStorage.setItem("token", action.payload.token);
                    localStorage.setItem(
                        "expirationDate",
                        new Date(action.payload.expires_at).toString()
                    );

                    delete action.payload.data.password;
                    state.token = action.payload.token;
                    state.data = action.payload.data;
                    state.role = "admin";
                    state.status = Status.IDLE;

                    checkAuthTimeout(
                        action.payload.expires_at - new Date().getTime()
                    );
                }
            })
            .addCase(adminLogin.rejected, (state, action) => {
                state.token = null;
                state.data = null;
                if (action.error.message)
                    state.message = message(action.error.message, "danger");
                state.status = Status.FAILED;
            });
    },
});

export const { logout } = authSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.auth.value)`
export const selectAuth = (state: AppState) => state.auth;

export default authSlice.reducer;
